# Generated by Django 4.1.2 on 2022-10-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='user_id',
        ),
    ]
